// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      try {
        const { data, error } = await supabase.auth.signInWithOAuth({
          provider: (provider === "lovable" ? "google" : provider) as "google" | "apple",
          options: {
            redirectTo: opts?.redirect_uri || `${typeof window !== "undefined" ? window.location.origin : ""}/dashboard`,
            queryParams: opts?.extraParams,
          },
        });

        if (error) {
          return { error };
        }

        return { data, redirected: true, error: null };
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
    },
  },
};
