/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccessDeniedRouteImport } from './routes/_authenticated/access-denied'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAnalyzeRouteImport } from './routes/_authenticated/analyze'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedCareerTimelineRouteImport } from './routes/_authenticated/career-timeline'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedCoverLetterRouteImport } from './routes/_authenticated/cover-letter'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated/interview'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedLinkedinOptimizerRouteImport } from './routes/_authenticated/linkedin-optimizer'
import { Route as AuthenticatedOfferEvaluatorRouteImport } from './routes/_authenticated/offer-evaluator'
import { Route as AuthenticatedOnboardingPlanRouteImport } from './routes/_authenticated/onboarding-plan'
import { Route as AuthenticatedResumesRouteImport } from './routes/_authenticated/resumes'
import { Route as AuthenticatedSalaryRouteImport } from './routes/_authenticated/salary'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedCoachIndexRouteImport } from './routes/_authenticated/coach/index'
import { Route as AuthenticatedCoachIdRouteImport } from './routes/_authenticated/coach/$id'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedReportsIdRouteImport } from './routes/_authenticated/reports/$id'
import { Route as AuthenticatedScreeningIndexRouteImport } from './routes/_authenticated/screening/index'
import { Route as AuthenticatedScreeningIdRouteImport } from './routes/_authenticated/screening/$id'
import { Route as ApiPublicV1AnalyzeRouteImport } from './routes/api/public/v1/analyze'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccessDeniedRoute =
  AuthenticatedAccessDeniedRouteImport.update({
    id: '/access-denied',
    path: '/access-denied',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyzeRoute = AuthenticatedAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareerTimelineRoute =
  AuthenticatedCareerTimelineRouteImport.update({
    id: '/career-timeline',
    path: '/career-timeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoverLetterRoute =
  AuthenticatedCoverLetterRouteImport.update({
    id: '/cover-letter',
    path: '/cover-letter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinkedinOptimizerRoute =
  AuthenticatedLinkedinOptimizerRouteImport.update({
    id: '/linkedin-optimizer',
    path: '/linkedin-optimizer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfferEvaluatorRoute =
  AuthenticatedOfferEvaluatorRouteImport.update({
    id: '/offer-evaluator',
    path: '/offer-evaluator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingPlanRoute =
  AuthenticatedOnboardingPlanRouteImport.update({
    id: '/onboarding-plan',
    path: '/onboarding-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumesRoute = AuthenticatedResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalaryRoute = AuthenticatedSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachIndexRoute = AuthenticatedCoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachIdRoute = AuthenticatedCoachIdRouteImport.update({
  id: '/coach/$id',
  path: '/coach/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIdRoute = AuthenticatedReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScreeningIndexRoute =
  AuthenticatedScreeningIndexRouteImport.update({
    id: '/screening/',
    path: '/screening/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScreeningIdRoute =
  AuthenticatedScreeningIdRouteImport.update({
    id: '/screening/$id',
    path: '/screening/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicV1AnalyzeRoute = ApiPublicV1AnalyzeRouteImport.update({
  id: '/api/public/v1/analyze',
  path: '/api/public/v1/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/access-denied': typeof AuthenticatedAccessDeniedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/career-timeline': typeof AuthenticatedCareerTimelineRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/linkedin-optimizer': typeof AuthenticatedLinkedinOptimizerRoute
  '/offer-evaluator': typeof AuthenticatedOfferEvaluatorRoute
  '/onboarding-plan': typeof AuthenticatedOnboardingPlanRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/salary': typeof AuthenticatedSalaryRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/coach/$id': typeof AuthenticatedCoachIdRoute
  '/reports/$id': typeof AuthenticatedReportsIdRoute
  '/screening/$id': typeof AuthenticatedScreeningIdRoute
  '/coach/': typeof AuthenticatedCoachIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/screening/': typeof AuthenticatedScreeningIndexRoute
  '/api/public/v1/analyze': typeof ApiPublicV1AnalyzeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/access-denied': typeof AuthenticatedAccessDeniedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/career-timeline': typeof AuthenticatedCareerTimelineRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/linkedin-optimizer': typeof AuthenticatedLinkedinOptimizerRoute
  '/offer-evaluator': typeof AuthenticatedOfferEvaluatorRoute
  '/onboarding-plan': typeof AuthenticatedOnboardingPlanRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/salary': typeof AuthenticatedSalaryRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/coach/$id': typeof AuthenticatedCoachIdRoute
  '/reports/$id': typeof AuthenticatedReportsIdRoute
  '/screening/$id': typeof AuthenticatedScreeningIdRoute
  '/coach': typeof AuthenticatedCoachIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/screening': typeof AuthenticatedScreeningIndexRoute
  '/api/public/v1/analyze': typeof ApiPublicV1AnalyzeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/access-denied': typeof AuthenticatedAccessDeniedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analyze': typeof AuthenticatedAnalyzeRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/career-timeline': typeof AuthenticatedCareerTimelineRoute
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interview': typeof AuthenticatedInterviewRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/linkedin-optimizer': typeof AuthenticatedLinkedinOptimizerRoute
  '/_authenticated/offer-evaluator': typeof AuthenticatedOfferEvaluatorRoute
  '/_authenticated/onboarding-plan': typeof AuthenticatedOnboardingPlanRoute
  '/_authenticated/resumes': typeof AuthenticatedResumesRoute
  '/_authenticated/salary': typeof AuthenticatedSalaryRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/coach/$id': typeof AuthenticatedCoachIdRoute
  '/_authenticated/reports/$id': typeof AuthenticatedReportsIdRoute
  '/_authenticated/screening/$id': typeof AuthenticatedScreeningIdRoute
  '/_authenticated/coach/': typeof AuthenticatedCoachIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/screening/': typeof AuthenticatedScreeningIndexRoute
  '/api/public/v1/analyze': typeof ApiPublicV1AnalyzeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/access-denied'
    | '/admin'
    | '/analyze'
    | '/billing'
    | '/career-timeline'
    | '/compare'
    | '/cover-letter'
    | '/dashboard'
    | '/interview'
    | '/jobs'
    | '/linkedin-optimizer'
    | '/offer-evaluator'
    | '/onboarding-plan'
    | '/resumes'
    | '/salary'
    | '/studio'
    | '/coach/$id'
    | '/reports/$id'
    | '/screening/$id'
    | '/coach/'
    | '/reports/'
    | '/screening/'
    | '/api/public/v1/analyze'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/access-denied'
    | '/admin'
    | '/analyze'
    | '/billing'
    | '/career-timeline'
    | '/compare'
    | '/cover-letter'
    | '/dashboard'
    | '/interview'
    | '/jobs'
    | '/linkedin-optimizer'
    | '/offer-evaluator'
    | '/onboarding-plan'
    | '/resumes'
    | '/salary'
    | '/studio'
    | '/coach/$id'
    | '/reports/$id'
    | '/screening/$id'
    | '/coach'
    | '/reports'
    | '/screening'
    | '/api/public/v1/analyze'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/access-denied'
    | '/_authenticated/admin'
    | '/_authenticated/analyze'
    | '/_authenticated/billing'
    | '/_authenticated/career-timeline'
    | '/_authenticated/compare'
    | '/_authenticated/cover-letter'
    | '/_authenticated/dashboard'
    | '/_authenticated/interview'
    | '/_authenticated/jobs'
    | '/_authenticated/linkedin-optimizer'
    | '/_authenticated/offer-evaluator'
    | '/_authenticated/onboarding-plan'
    | '/_authenticated/resumes'
    | '/_authenticated/salary'
    | '/_authenticated/studio'
    | '/_authenticated/coach/$id'
    | '/_authenticated/reports/$id'
    | '/_authenticated/screening/$id'
    | '/_authenticated/coach/'
    | '/_authenticated/reports/'
    | '/_authenticated/screening/'
    | '/api/public/v1/analyze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicV1AnalyzeRoute: typeof ApiPublicV1AnalyzeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/access-denied': {
      id: '/_authenticated/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AuthenticatedAccessDeniedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analyze': {
      id: '/_authenticated/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AuthenticatedAnalyzeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career-timeline': {
      id: '/_authenticated/career-timeline'
      path: '/career-timeline'
      fullPath: '/career-timeline'
      preLoaderRoute: typeof AuthenticatedCareerTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cover-letter': {
      id: '/_authenticated/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof AuthenticatedCoverLetterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/linkedin-optimizer': {
      id: '/_authenticated/linkedin-optimizer'
      path: '/linkedin-optimizer'
      fullPath: '/linkedin-optimizer'
      preLoaderRoute: typeof AuthenticatedLinkedinOptimizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offer-evaluator': {
      id: '/_authenticated/offer-evaluator'
      path: '/offer-evaluator'
      fullPath: '/offer-evaluator'
      preLoaderRoute: typeof AuthenticatedOfferEvaluatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding-plan': {
      id: '/_authenticated/onboarding-plan'
      path: '/onboarding-plan'
      fullPath: '/onboarding-plan'
      preLoaderRoute: typeof AuthenticatedOnboardingPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumes': {
      id: '/_authenticated/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AuthenticatedResumesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary': {
      id: '/_authenticated/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof AuthenticatedSalaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach/': {
      id: '/_authenticated/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthenticatedCoachIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach/$id': {
      id: '/_authenticated/coach/$id'
      path: '/coach/$id'
      fullPath: '/coach/$id'
      preLoaderRoute: typeof AuthenticatedCoachIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id': {
      id: '/_authenticated/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AuthenticatedReportsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/screening/': {
      id: '/_authenticated/screening/'
      path: '/screening'
      fullPath: '/screening/'
      preLoaderRoute: typeof AuthenticatedScreeningIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/screening/$id': {
      id: '/_authenticated/screening/$id'
      path: '/screening/$id'
      fullPath: '/screening/$id'
      preLoaderRoute: typeof AuthenticatedScreeningIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v1/analyze': {
      id: '/api/public/v1/analyze'
      path: '/api/public/v1/analyze'
      fullPath: '/api/public/v1/analyze'
      preLoaderRoute: typeof ApiPublicV1AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessDeniedRoute: typeof AuthenticatedAccessDeniedRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyzeRoute: typeof AuthenticatedAnalyzeRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCareerTimelineRoute: typeof AuthenticatedCareerTimelineRoute
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedCoverLetterRoute: typeof AuthenticatedCoverLetterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedLinkedinOptimizerRoute: typeof AuthenticatedLinkedinOptimizerRoute
  AuthenticatedOfferEvaluatorRoute: typeof AuthenticatedOfferEvaluatorRoute
  AuthenticatedOnboardingPlanRoute: typeof AuthenticatedOnboardingPlanRoute
  AuthenticatedResumesRoute: typeof AuthenticatedResumesRoute
  AuthenticatedSalaryRoute: typeof AuthenticatedSalaryRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedCoachIdRoute: typeof AuthenticatedCoachIdRoute
  AuthenticatedReportsIdRoute: typeof AuthenticatedReportsIdRoute
  AuthenticatedScreeningIdRoute: typeof AuthenticatedScreeningIdRoute
  AuthenticatedCoachIndexRoute: typeof AuthenticatedCoachIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedScreeningIndexRoute: typeof AuthenticatedScreeningIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessDeniedRoute: AuthenticatedAccessDeniedRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyzeRoute: AuthenticatedAnalyzeRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCareerTimelineRoute: AuthenticatedCareerTimelineRoute,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedCoverLetterRoute: AuthenticatedCoverLetterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedLinkedinOptimizerRoute: AuthenticatedLinkedinOptimizerRoute,
  AuthenticatedOfferEvaluatorRoute: AuthenticatedOfferEvaluatorRoute,
  AuthenticatedOnboardingPlanRoute: AuthenticatedOnboardingPlanRoute,
  AuthenticatedResumesRoute: AuthenticatedResumesRoute,
  AuthenticatedSalaryRoute: AuthenticatedSalaryRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedCoachIdRoute: AuthenticatedCoachIdRoute,
  AuthenticatedReportsIdRoute: AuthenticatedReportsIdRoute,
  AuthenticatedScreeningIdRoute: AuthenticatedScreeningIdRoute,
  AuthenticatedCoachIndexRoute: AuthenticatedCoachIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedScreeningIndexRoute: AuthenticatedScreeningIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicV1AnalyzeRoute: ApiPublicV1AnalyzeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
