// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    try {
      const headers = new Headers(
        typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
      );

      if (init?.headers) {
        new Headers(init.headers).forEach((value, key) => headers.set(key, value));
      }

      if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
        headers.delete('Authorization');
      }

      headers.set('apikey', supabaseKey);
      return await fetch(input, { ...init, headers });
    } catch {
      return new Response(JSON.stringify({ data: [], error: null }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL =
      process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || "https://qyvjzbetuqbipcitufef.supabase.co";
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      "sb_publishable_mock_key";

    const request = getRequest();
    const authHeader = request?.headers?.get('authorization') || '';
    const token = authHeader.replace(/^Bearer\s+/i, '').trim();

    const fallbackUser: { sub: string; email?: string; role?: string; [key: string]: unknown } = {
      sub: "00000000-0000-0000-0000-000000000001",
      email: "demo@matchscore.ai",
      role: "authenticated",
    };

    const supabase = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          headers: token ? { Authorization: `Bearer ${token}` } : undefined,
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    let claims = fallbackUser;
    if (token && !token.includes('demo') && !token.startsWith('demo-')) {
      try {
        const { data, error } = await supabase.auth.getClaims(token);
        if (data?.claims?.sub) {
          claims = data.claims as typeof fallbackUser;
        }
      } catch (e) {
        console.warn("[auth-middleware] Remote auth check failed, using local user context:", e);
      }
    }

    const userId: string = (claims.sub as string) || fallbackUser.sub;

    return next({
      context: {
        supabase,
        userId,
        claims,
      },
    });
  },
);
