// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const DEMO_USER = {
  id: "00000000-0000-0000-0000-000000000001",
  app_metadata: { provider: "google", providers: ["google", "email"] },
  user_metadata: { full_name: "Demo Candidate" },
  aud: "authenticated",
  confirmation_sent_at: new Date().toISOString(),
  confirmed_at: new Date().toISOString(),
  created_at: new Date().toISOString(),
  email: "demo@matchscore.ai",
  email_confirmed_at: new Date().toISOString(),
  identities: [],
  is_anonymous: false,
  last_sign_in_at: new Date().toISOString(),
  phone: "",
  role: "authenticated",
  updated_at: new Date().toISOString(),
};

export const DEMO_SESSION = {
  access_token: "demo-jwt-token.demo.signature",
  token_type: "bearer",
  expires_in: 86400,
  expires_at: Math.floor(Date.now() / 1000) + 86400,
  refresh_token: "demo-refresh-token",
  user: DEMO_USER,
};

export function isDemoMode(): boolean {
  if (typeof window === "undefined") return false;
  return localStorage.getItem("matchscore_demo_mode") === "true";
}

export function loginDemoUser(fullName = "Demo Candidate", email = "demo@matchscore.ai") {
  if (typeof window !== "undefined") {
    localStorage.setItem("matchscore_demo_mode", "true");
    const user = {
      ...DEMO_USER,
      email,
      user_metadata: { full_name: fullName },
    };
    localStorage.setItem("matchscore_demo_user", JSON.stringify(user));
    window.location.href = "/dashboard";
  }
}

export function logoutDemoUser() {
  if (typeof window !== "undefined") {
    localStorage.removeItem("matchscore_demo_mode");
    localStorage.removeItem("matchscore_demo_user");
    window.location.href = "/auth";
  }
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    try {
      const headers = new Headers(
        typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
      );

      if (init?.headers) {
        new Headers(init.headers).forEach((value, key) => headers.set(key, value));
      }

      if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
        headers.delete('Authorization');
      }

      headers.set('apikey', supabaseKey);
      return await fetch(input, { ...init, headers });
    } catch {
      return new Response(JSON.stringify({ data: [], error: null }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }
  };
}

function createSupabaseClient() {
  const SUPABASE_URL =
    (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_URL) ||
    process.env.VITE_SUPABASE_URL ||
    process.env.SUPABASE_URL ||
    "https://qyvjzbetuqbipcitufef.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY) ||
    process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    "sb_publishable_mock_key";

  const rawClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  return new Proxy(rawClient, {
    get(target, prop, receiver) {
      if (prop === 'auth') {
        const rawAuth = target.auth;
        return new Proxy(rawAuth, {
          get(authTarget, authProp) {
            if (authProp === 'getUser') {
              return async (jwt?: string) => {
                if (isDemoMode()) {
                  const saved = typeof window !== 'undefined' ? localStorage.getItem("matchscore_demo_user") : null;
                  const u = saved ? JSON.parse(saved) : DEMO_USER;
                  return { data: { user: u }, error: null };
                }
                try {
                  const res = await authTarget.getUser(jwt);
                  if (res.data?.user) return res;
                } catch {
                  // Fallback
                }
                return { data: { user: null }, error: null };
              };
            }

            if (authProp === 'getSession') {
              return async () => {
                if (isDemoMode()) {
                  const saved = typeof window !== 'undefined' ? localStorage.getItem("matchscore_demo_user") : null;
                  const u = saved ? JSON.parse(saved) : DEMO_USER;
                  return { data: { session: { ...DEMO_SESSION, user: u } }, error: null };
                }
                try {
                  const res = await authTarget.getSession();
                  if (res.data?.session) return res;
                } catch {
                  // Fallback
                }
                return { data: { session: null }, error: null };
              };
            }

            if (authProp === 'onAuthStateChange') {
              return (callback: (event: string, session: any) => void) => {
                if (isDemoMode()) {
                  const saved = typeof window !== 'undefined' ? localStorage.getItem("matchscore_demo_user") : null;
                  const u = saved ? JSON.parse(saved) : DEMO_USER;
                  try {
                    callback("SIGNED_IN", { ...DEMO_SESSION, user: u });
                  } catch {}
                }
                try {
                  return authTarget.onAuthStateChange(callback);
                } catch {
                  return {
                    data: {
                      subscription: {
                        unsubscribe: () => {},
                      },
                    },
                  };
                }
              };
            }

            if (authProp === 'signOut') {
              return async () => {
                if (isDemoMode()) {
                  logoutDemoUser();
                  return { error: null };
                }
                try {
                  return await authTarget.signOut();
                } catch {
                  logoutDemoUser();
                  return { error: null };
                }
              };
            }

            return Reflect.get(authTarget, authProp);
          },
        });
      }
      return Reflect.get(target, prop, receiver);
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
